language: racket

env:
 - RACKET_VERSION=6.1

before_install:
- cd ..
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

install:

before_script:

script:
 - /usr/racket/bin/raco pkg install --deps search-auto --link seq-no-order
 - /usr/racket/bin/raco test -p seq-no-order

after_script:
